stages:
  - test
  - build
  - format

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  GIT_SUBMODULE_STRATEGY: normal

build:
  stage: build
  script:
    RUST_BACKTRACE=1 cargo build

format:
  stage: format
  script:
    cargo fmt --all -- --check

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

cache:
  paths:
    - dynamorio/
    - cargo/
    - target/
